Rework workspace & VM setup.
Always run workspace setup prior to executing a build; make the setup
routine a no-op if no changes are needed.  Store the checksum of the most
recently extracted closed binaries to enable this.  Perform the workspace
setup on the host rather than the guest to reduce time required.o

Separate VM setup from starting the VM, so the build step can just ensure
the VM has been started, regardless of whether it needs to be setup.

diff --git a/vig-common/common b/vig-common/common
--- a/vig-common/common
+++ b/vig-common/common
@@ -69,3 +69,17 @@ vig_reexec_noreturn() {
 	exec ${VIG_PATH} ${VIG_ARGS} $*
 	exit 127 # NOTREACHED
 }
+
+md5_file() {
+	fpath=$1
+	if which md5sum >/dev/null 2>&1; then
+		md5sum $fpath | awk '{print $1}'
+	elif which md5 >/dev/null 2>&1; then
+		md5 $fpath | awk '{print $4}'
+	elif which openssl >/dev/null 2>&1; then
+		openssl md5 $fpath | awk '{print $2}'
+	else
+		echo "*** ERROR: Can't find an MD5 implementation" >&2
+		exit 1
+	fi
+}
